apiVersion: skaffold/v2beta8
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: true
  artifacts:
    - image: rpgms/quest-npc-app
      context: quest-npc
      docker:
        dockerfile: Dockerfile.dev
    - image: rpgms/world
      context: world
      docker:
        dockerfile: Dockerfile.dev
    - image: rpgms/story-teller
      context: story-teller
      docker:
        dockerfile: Dockerfile.dev
deploy:
  kustomize:
    paths: [
      "quest-npc/deploy/overlays/prod",
      "world/deploy/overlays/prod",
      "story-teller/deploy/overlays/prod",
      ]
profiles:
- name: dev
  activation:
  - command: dev # Always activate this profile for the 'skaffold dev' command
  deploy:
    kustomize:
      paths: [
        "quest-npc/deploy/overlays/dev",
        "world/deploy/overlays/dev",
        "story-teller/deploy/overlays/dev",
        ]
  portForward:
    - resourceType: deployment
      resourceName: quest-npc
      port: 2222
      localPort: 2222
    - resourceType: deployment
      resourceName: quest-npc-db
      port: 5432
      localPort: 5432
    - resourceType: deployment
      resourceName: world
      port: 3333
      localPort: 3333
    - resourceType: deployment
      resourceName: story-teller
      port: 4444
      localPort: 4444
- name: prod
  deploy:
    kustomize:
      paths: [
        "quest-npc/deploy/overlays/prod",
        "world/deploy/overlays/prod",
        "story-teller/deploy/overlays/prod",
        ]
