apiVersion: skaffold/v2beta8
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: true
  artifacts:
    - image: rpgms/world
      context: .
      docker:
        dockerfile: Dockerfile.dev
deploy:
  kustomize:
    paths: [
      "deploy/overlays/prod",
      ]
profiles:
- name: dev
  activation:
  - command: dev # Always activate this profile for the 'skaffold dev' command
  deploy:
    kustomize:
      paths: [
        "deploy/overlays/dev",
        ]
  portForward:
    - resourceType: deployment
      resourceName: world
      port: 3333
      localPort: 3333
- name: prod
  deploy:
    kustomize:
      paths: [
        "deploy/overlays/prod",
        ]
- name: debug
  activation:
  - command: debug # Always activate this profile for the 'skaffold debug' command
  build:
    tagPolicy:
      gitCommit: {}
    local:
      push: true
    artifacts:
      - image: rpgms/world
        context: .
        docker:
          dockerfile: Dockerfile.debug
  deploy:
    kustomize:
      paths: [
        "deploy/overlays/debug",
        ]
