apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: world
build:
  artifacts:
  - image: rpgms/world
    docker:
      dockerfile: Dockerfile.dev
  tagPolicy:
    gitCommit: {}
deploy:
  kustomize:
    paths: ["deploy/overlays/dev"]
