apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: quest-npc-app
build:
  artifacts:
  - image: rpgms/quest-npc-app
    docker:
      dockerfile: Dockerfile.dev
  tagPolicy:
    gitCommit: {}
deploy:
  kustomize:
    paths: ["deploy/overlays/dev"]
