apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: quest-npc
build:
  artifacts:
  - image: rpgms/quest-npc
  tagPolicy:
    gitCommit: {}
deploy:
  kustomize:
    paths: ["deploy/overlays/prod"]
