apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest-npc-app
  labels:
    app: quest-npc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quest-npc-app
  template:
    metadata:
      labels:
        app: quest-npc-app
    spec:
      containers:
        - name: quest-npc-app
          image: rpgms/quest-npc-app
          ports:
            - containerPort: 2222
          resources:
            limits: { cpu: .3, memory: 128M }
            requests: { cpu: .1, memory: 32M }
