apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest-npc
  labels:
    app: quest-npc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quest-npc
  template:
    metadata:
      labels:
        app: quest-npc
    spec:
      containers:
        - name: quest-npc
          image: rpgms/quest-npc
          ports:
            - containerPort: 2222
          resources:
            limits: { cpu: .3, memory: 128M }
            requests: { cpu: .1, memory: 32M }
