apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
  labels:
    app: world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
        - name: world
          image: rpgms/world
          ports:
            - containerPort: 3333
          resources:
            limits: { cpu: .3, memory: 128M }
            requests: { cpu: .1, memory: 32M }
